### ISSUE TITLE
ValueError: Unsupported non-standard amino acid found:  DC in parsers.py

### ISSUE THREAD

**Issue by rraadd88** [haddocking/prodigy#11]
Hi, I encountered this error after running prodigy on some PDB ids (eg. 4JGJ, 4H10, 4XRS).
Seems that some residue names are non-standard for some reason.

Demo code:
I am using python3_package branch.
```
> prodigy 4XRS.pdb  --selection A G --contact_list --pymol_selection
[+] Reading structure file: 4XRS.pdb
Traceback (most recent call last):
  File "prodigy", line 11, in <module>
    load_entry_point('prodigy', 'console_scripts', 'prodigy')()
  File "prodigy/prodigy/predict_IC.py", line 308, in main
    structure, n_chains, n_res = parse_structure(struct_path)
  File "prodigy/prodigy/lib/parsers.py", line 141, in parse_structure
    return (validate_structure(s),
  File "prodigy/prodigy/lib/parsers.py", line 87, in validate_structure
    raise ValueError('Unsupported non-standard amino acid found: {0}'.format(res.resname))
ValueError: Unsupported non-standard amino acid found:  DC
```
I wonder if there is any easy way to get around this error.

**Comment by amjjbonvin** [comment]
DC is a nucleotide and prodigy only supports proteins and standard amino-acids

**Comment by brianjimenez** [comment]
Nucleotide are not supported by `prodigy`, library is handling the issue properly raising a `ValueError` with a meaningful message.
